# Project information
site_name: Moov Documentation
site_description: Open Source Financial Technology Micro Services
site_url: https://docs.moov.io/

# Repository
repo_name: moov-io/docs
repo_url: https://github.com/moov-io/docs/

# Copyright
copyright: 'Copyright &copy; 2017 - 2019 Moov Authors'

# Configuration
theme:
  name: 'material'
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # default values
  language: en
  feature:
    tabs: true
  palette:
    primary: pink
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo:
    icon: "\uE80C"

# Plugins
plugins:
  - search

extra:
  social:
    - type: globe
      link: https://moov.io
    - type: github-alt
      link: https://github.com/moov-io
    - type: twitter
      link: https://twitter.com/moov_io
      #- type: linkedin
      #  link: https://linkedin.com/in/squidfunk

extra_javascript:
  - 'assets/javascript/github-buttons.js'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
- Introduction:
  - Welcome: index.md
  - Technology: technology.md
  - 'How can I use Moov?':
    - Capabilities: how/capabilities.md
    - First Party Payments: how/first-party.md
    - SaaS Bundling Payments: how/saas-bundle-payment.md
    - Examples:
      - Bike Company: how/examples/bike-sales.md
      - Game Developer: how/examples/game-developer.md
      - HOA Vendor: how/examples/hoa.md
  - FAQ:
    - Local Dev: faq/local-dev.md
    - Production: faq/production.md
- Customers:
    - Getting Started: customers/index.md
    - Account Validation: customers/account-validation.md
    - 'Checks (KYC/AML)': customers/checks.md
    - Disclaimers: customers/disclaimers.md
    - Documents: customers/documents.md
    - Local Dev: customers/local-dev.md
- PayGate:
  - Getting Started: paygate/index.md
  - Concepts:
    - ACH Operations: paygate/concepts/ach.md
    - Advanced Routing: paygate/concepts/advanced-routing.md
    - High Availability: paygate/concepts/ha.md
  - Configuration: paygate/config.md
  - Dependencies:
    - Customers: paygate/dependencies/customers.md
  - Local Dev: paygate/local-dev.md
  - Admin Endpoints: paygate/admin.md
  # - Troubleshooting: paygate/troubleshooting.md
  # - Frequently Asked Questions: paygate/faq.md
  - Vocab: paygate/vocab.md

# Google analytics
google_analytics: ['UA-118148273-1', 'moov.io']
