# Project information
site_name: Moov Documentation
site_description: Open Source Financial Technology Micro Services
site_url: https://docs.moov.io/

# Repository
repo_name: moov-io/docs
repo_url: https://github.com/moov-io/docs/

# Copyright
copyright: 'Copyright &copy; 2017 - 2019 Moov Authors'

# Configuration
theme:
  name: 'material'
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # default values
  language: en
  feature:
    tabs: true
  palette:
    primary: pink
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo:
    icon: "\uE80C"

# Plugins
plugins:
  - search

extra:
  social:
    - type: globe
      link: https://moov.io
    - type: github-alt
      link: https://github.com/moov-io
    - type: twitter
      link: https://twitter.com/moov_io
      #- type: linkedin
      #  link: https://linkedin.com/in/squidfunk

extra_javascript:
  - 'assets/javascript/github-buttons.js'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
- Introduction:
  - Welcome: index.md
- ACH:
  - Getting Started: ach/index.md
  - Tutorials:
      - 'Create an ACH FIle': ach/create-file.md
      - 'Merging ACH Files': ach/merging-files.md
  - ACH Developers:
    - 'Intro to ACH': ach/intro.md
    - 'ACH File Structure': ach/file-structure.md
    - 'Picking an SEC Code': ach/sec-codes-table.md
- FED:
  - Overview: fed/index.md
  - 'FED File Structure': fed/file-structure.md
- 'Image Cash Letter':
  - Overview: icl/index.md
  - 'ICL File Structure': icl/file-structure.md
- OFAC:
  - Overview: ofac/index.md
  - 'OFAC File Structure': ofac/file-structure.md
- Paygate:
  - Overview: paygate/index.md
- WIRE:
  - Overview: wire/index.md
  - 'WIRE Fed Wire Message Structure': wire/fedWireMessage-Structure.md
  - 'Date': wire/DateMMDD.md
  - 'Time': wire/TimeHHMM.md
  - 'Address': wire/address.md
  - 'Remittance Data': wire/remittanceData.md

# Google analytics
google_analytics: ['UA-118148273-1', 'moov.io']
