site_name: Moov Documentation
pages:
- Overview: index.md
- About: about.md
- ACH:
  - Overview: ach/index.md
  - 'ACH File Structure': ach/file-structure.md
  - 'Picking an SEC Code': ach/sec-codes-table.md
  - 'Merging ACH Files': ach/merging-files.md
- FED:
  - Overview: fed/index.md
  - 'FED File Structure': fed/file-structure.md
- 'Image Cash Letter':
  - Overview: icl/index.md
  - 'ICL File Structure': icl/file-structure.md
- OFAC:
  - Overview: ofac/index.md
  - 'OFAC File Structure': ofac/file-structure.md
- WIRE:
  -  Overview: wire/index.md
  - 'WIRE Fed Wire Message Structure': wire/fedWireMessage-Structure.md
  - 'Date': wire/DateMMDD.md
  - 'Time': wire/TimeHHMM.md
  - 'Address': wire/address.md
  - 'Remittance Data': wire/remittanceData.md
- Tutorials:
    - 'Running ACH Server': tutorials/ach-server.md
    - 'Local Dev with Moov': tutorials/local-dev.md
theme: readthedocs
extra_css:
  - extra.css
repo_url: https://github.com/moov-io/docs/
google_analytics: ['UA-118148273-1', 'moov.io']
