site_name: Moov Documentation
pages:
- Overview: index.md
- Developers Guide:
    - Reference: reference.md
    - 'ACH File Structure': ACH_File_Structure.md
    - 'X9 File Structure': X9_File_Structure.md
- Tutorials:
    - 'Running ACH Server': ach-server.md
- About: about.md

theme: readthedocs
extra_css:
  - extra.css
repo_url: https://github.com/moov-io/docs/
google_analytics: ['UA-118148273-1', 'moov.io']
