site_name: Moov Documentation
pages:
    - Overview: index.md
    - ACH: ach.md
    - Reference: reference.md
    - About: about.md

theme: readthedocs
repo_url: https://github.com/moov-io/docs/
google_analytics: ['UA-118148273-1', 'moov.io']